// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as KifuService from "./kifuservice.js";
import * as ServerService from "./serverservice.js";
export {
    KifuService,
    ServerService
};

export type {
    GameDetail,
    GameSummary,
    SearchQuery,
    ServerStatus
} from "./models.js";
