// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KifuService は棋譜の取得・保存・削除をフロントに公開する。
 * ロジックは shinte/kicho の Library 側にあり、ここは変換と入力チェックだけ行う。
 * 
 * 取得(Fetch)と保存(Save)は別操作にしてある。対局中の棋譜は随時更新されるため、
 * 「取得して内容を確認 → その表示内容をそのまま保存」という流れにするのが目的で、
 * 保存時にサイトへ取り直しに行くことはない。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Count は保存件数を返す(検索結果と全体を比べて表示するため)。
 */
export function Count(): $CancellablePromise<number> {
    return $Call.ByID(1685092699);
}

/**
 * Delete は棋譜を削除する。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1983321903, id);
}

/**
 * Fetch はライブ中継から棋譜を取得する(保存はしない)。
 * 
 * 取得元は入力から判別する。
 * 
 *   - live.shogi.or.jp の URL      → 日本将棋連盟の棋譜中継
 *   - それ以外(URL / 棋譜 ID)      → 読売(竜王戦)
 * 
 * 対局中の棋譜も取得できる(その場合 Finished は false)。
 */
export function Fetch(input: string): $CancellablePromise<$models.GameDetail> {
    return $Call.ByID(1177840348, input);
}

/**
 * Get は棋譜1件を KIF 本文つきで返す。
 */
export function Get(id: string): $CancellablePromise<$models.GameDetail> {
    return $Call.ByID(485802688, id);
}

/**
 * ImportKIF は KIF テキストを解析して保存する(貼り付け登録)。
 * 取得元での一意な ID が無いため、毎回新しい棋譜として登録される。
 */
export function ImportKIF(text: string): $CancellablePromise<$models.GameSummary> {
    return $Call.ByID(391944577, text);
}

/**
 * ImportURL は URL から KIF を取得して保存する。
 */
export function ImportURL(rawURL: string): $CancellablePromise<$models.GameSummary> {
    return $Call.ByID(492089658, rawURL);
}

/**
 * List は保存済み棋譜の一覧を新しい順に返す(KIF 本文は含まない)。
 */
export function List(): $CancellablePromise<$models.GameSummary[] | null> {
    return $Call.ByID(4258662380);
}

/**
 * PreviewKIF は KIF テキストを解析して内容を返す(保存はしない)。
 * 貼り付け登録の前に、何が読み取れたかを確認するために使う。
 */
export function PreviewKIF(text: string): $CancellablePromise<$models.GameDetail> {
    return $Call.ByID(1312719722, text);
}

/**
 * PreviewURL は URL から KIF を取得して解析する(保存はしない)。
 */
export function PreviewURL(rawURL: string): $CancellablePromise<$models.GameDetail> {
    return $Call.ByID(1242984209, rawURL);
}

/**
 * Refresh は取得済みのカードを取り直す。
 * 
 * 入力欄からの Fetch と違って取得元が分かっているので、判別も
 * 中継ページ→棋譜 ID の往復も挟まらず、棋譜 ID で直接取りに行く。
 */
export function Refresh(source: string, sourceID: string): $CancellablePromise<$models.GameDetail> {
    return $Call.ByID(3395125263, source, sourceID);
}

/**
 * Save は Fetch で取得して画面に表示している内容をそのまま保存する。
 * サイトへ取り直しには行かない。
 * 
 * 同じ棋譜を保存し直しても重複せず、既存の ID を維持したまま内容が更新される
 * (対局中に保存 → 終局後に取り直して保存、で同じ ID のまま最新になる)。
 */
export function Save(d: $models.GameDetail): $CancellablePromise<$models.GameSummary> {
    return $Call.ByID(1187777633, d);
}

/**
 * Search は条件に合う棋譜を新しい順に返す(KIF 本文は含まない)。
 */
export function Search(q: $models.SearchQuery): $CancellablePromise<$models.GameSummary[] | null> {
    return $Call.ByID(1724565080, q);
}
