// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameDetail は棋譜1件の詳細(KIF 本文つき)。
 * Fetch が返したものをそのまま Save に渡せる。
 */
export interface GameDetail {
    "id": string;
    "source": string;
    "sourceId": string;

    /**
     * SourceURL は取得元の URL(URL 取り込みのみ)。
     */
    "sourceUrl": string;
    "event": string;
    "handicap": string;
    "place": string;
    "black": string;
    "white": string;

    /**
     * RFC3339。未設定なら空文字
     */
    "startedAt": string;

    /**
     * EndMark は終局の種別(例 "投了")。対局中は空。
     */
    "endMark": string;

    /**
     * Finished は終局済みかどうか。UI で手数の横に「(終局)」を出すのに使う。
     */
    "finished": boolean;
    "moves": number;
    "kif": string;
}

/**
 * GameSummary は一覧表示用の1件。
 */
export interface GameSummary {
    "id": string;
    "source": string;
    "sourceId": string;

    /**
     * SourceURL は取得元の URL(URL 取り込みのみ)。
     */
    "sourceUrl": string;
    "event": string;
    "handicap": string;
    "place": string;
    "black": string;
    "white": string;

    /**
     * RFC3339。未設定なら空文字
     */
    "startedAt": string;

    /**
     * EndMark は終局の種別(例 "投了")。対局中は空。
     */
    "endMark": string;

    /**
     * Finished は終局済みかどうか。UI で手数の横に「(終局)」を出すのに使う。
     */
    "finished": boolean;
    "moves": number;
}

/**
 * SearchQuery は検索条件。空の項目は「条件なし」。
 */
export interface SearchQuery {
    /**
     * Text は棋戦名・対局者・場所への部分一致。
     * 3文字以上なら索引(FTS5 trigram)が効く。それ未満は走査になる。
     */
    "text": string;

    /**
     * From / To は開始日の範囲。"YYYY-MM-DD" 形式。空なら無制限。
     */
    "from": string;
    "to": string;

    /**
     * FinishedOnly が true なら終局済みのみ。
     */
    "finishedOnly": boolean;

    /**
     * Limit は取得件数の上限(0 なら無制限)。
     */
    "limit": number;
}

/**
 * ServerStatus はサーバの現在状態。
 */
export interface ServerStatus {
    "running": boolean;

    /**
     * Addr は実際に listen しているアドレス(停止中は空)。
     */
    "addr": string;
    "host": string;
    "port": number;

    /**
     * Public が true なら localhost 以外に公開されている(UI で警告を出す)。
     */
    "public": boolean;

    /**
     * AutoStart はアプリ起動時に自動で listen するかどうか。
     */
    "autoStart": boolean;

    /**
     * URLs は外部ツールに貼れるベース URL の候補(末尾にスラッシュは付かない)。
     * 
     * 停止中でも設定値から組み立てて返す。棋譜 URL のコピーは
     * サーバが動いていなくても行えた方が便利なため(貼り付け先で使う頃には
     * 起動しておけばよい)。LAN 公開時は実際に到達できる LAN アドレスも含む。
     */
    "urls": string[] | null;
}
