// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerService は棋譜配信 HTTP サーバの設定と起動/停止をフロントに公開する。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * KifuURLs は保存済み棋譜(kicho 自前の ID)の URL を返す。
 * 外部ツールへ貼るための「URL コピー」で使う。先頭が localhost 版。
 */
export function KifuURLs(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3916915933, id);
}

/**
 * SourceURLs は取得元から直接取得する URL(ライブ経路)を返す。
 * 対局中の棋譜はこちらを渡す(外部ツールが開くたびにサイトから取り直す)。
 * 
 * サイトの URL ではなく kicho 経由の URL を返す。連盟の中継は Shift_JIS で
 * 配信されているので、kicho を通して UTF-8 に寄せたものを渡すため。
 */
export function SourceURLs(source: string, sourceID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1802713013, source, sourceID);
}

/**
 * Start は現在の設定でサーバを起動する。
 */
export function Start(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(1602833774);
}

/**
 * Status は現在の設定と稼働状態を返す。
 */
export function Status(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(1166105408);
}

/**
 * Stop はサーバを停止する。
 */
export function Stop(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(934708918);
}

/**
 * UpdateSettings は待ち受け設定を保存する。
 * 稼働中に変更した場合は、新しい設定で listen し直す。
 */
export function UpdateSettings(host: string, port: number, autoStart: boolean): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(690833946, host, port, autoStart);
}
